/* Autogenerated with kurento-module-creator */

#include "bienfirstappOpenCVImpl.hpp"
#include <KurentoException.hpp>

namespace kurento
{
namespace module
{
namespace bienfirstapp
{

bienfirstappOpenCVImpl::bienfirstappOpenCVImpl ()
{
}

/*
 * This function will be called with each new frame. mat variable
 * contains the current frame. You should insert your image processing code
 * here. Any changes in mat, will be sent through the Media Pipeline.
 */
void bienfirstappOpenCVImpl::process (cv::Mat &mat)
{
  // FIXME: Implement this
  throw KurentoException (NOT_IMPLEMENTED, "bienfirstappOpenCVImpl::process: Not implemented");
}



} /* bienfirstapp */
} /* module */
} /* kurento */
