/* Autogenerated with kurento-module-creator */

#ifndef __BIENFIRSTAPP_IMPL_HPP__
#define __BIENFIRSTAPP_IMPL_HPP__

#include "OpenCVFilterImpl.hpp"
#include "bienfirstapp.hpp"
#include <EventHandler.hpp>
#include <boost/property_tree/ptree.hpp>
#include "bienfirstappOpenCVImpl.hpp"

namespace kurento
{
namespace module
{
namespace bienfirstapp
{
class bienfirstappImpl;
} /* bienfirstapp */
} /* module */
} /* kurento */

namespace kurento
{
void Serialize (std::shared_ptr<kurento::module::bienfirstapp::bienfirstappImpl> &object, JsonSerializer &serializer);
} /* kurento */

namespace kurento
{
class MediaPipelineImpl;
} /* kurento */

namespace kurento
{
namespace module
{
namespace bienfirstapp
{

class bienfirstappImpl : public OpenCVFilterImpl, public virtual bienfirstapp, public virtual bienfirstappOpenCVImpl
{

public:

  bienfirstappImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline);

  virtual ~bienfirstappImpl() = default;

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType, std::shared_ptr<EventHandler> handler);
  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);

private:

  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* bienfirstapp */
} /* module */
} /* kurento */

#endif /*  __BIENFIRSTAPP_IMPL_HPP__ */
